# https://docs.docker.com/compose/compose-file/
# https://github.com/docker/awesome-compose
services:
  backend:
    build:
      context: backend
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: ${DB_USER}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
